### ISSUE TITLE
No module named ...

### ISSUE THREAD

**Issue by ZackMercury** [YafaRay/YafaRay-Blender#4]
My first experience with YafaRay, I just tried to install from zip, installed successfully, now can't enable it.
![image](https://user-images.githubusercontent.com/10474828/95086385-1c9c7000-0729-11eb-9925-14b87b2744e1.png)

**Comment by foreachthing** [comment]
It only works up to Blender 2.79, I think.

**Comment by odil24** [comment]
Latest Yafaray 3.5.1 just works on Blender 2.79 (a and b too). David isnt ported to Blender 2.8+ yet.

**Comment by DavidBluecame** [comment]
Hello,

odil24 is right, but there is a pre-alpha (incomplete and very experimental) build of v3.5.1 for Blender 2.82 here: https://github.com/YafaRay/Blender-Exporter28/releases 

(materials are very incomplete as nodes system is not yet implemented)

**Comment by DavidBluecame** [comment]
Open the "Assets" triangle to show the available builds

**Comment by ZackMercury** [comment]
Check what I'm trying to enable

**Comment by ZackMercury** [comment]
![image](https://user-images.githubusercontent.com/10474828/95112642-de637880-0749-11eb-85a6-62546e49f692.png)

**Comment by DavidBluecame** [comment]
Hello,

Perhaps the pre-alpha exporter I adapted for Blender 2.82 is not working in Blender 2.90? I'll check and let you know.

**Comment by DavidBluecame** [comment]
Hello,

I've just tested now in both Linux and Windows and the Blender28 builds can be installed in Blender v2.90.1 without problems:

![image](https://user-images.githubusercontent.com/3886025/95124502-d01a5a00-0753-11eb-9a60-6a1f3d8d9f60.png)

![image](https://user-images.githubusercontent.com/3886025/95124938-82522180-0754-11eb-87b8-993dd9958784.png)

I'm not certain about how are you installing the YafaRay addon? You can just download the correct one from https://github.com/YafaRay/Blender-Exporter28/releases in the assets triangle, and then install it with the "Install..." button in the Preferences->AddOns

If you are having issues it could be because you are doing something different, or maybe you still have some "remains" of a previous installation attempt of the "standard" version which is not good for v2.90.1?  In that case, remove any wrong YafaRay versions from Roaming->Blender, etc, and try again.

**Comment by DavidBluecame** [comment]
You need to download the correct build for your OS:

![image](https://user-images.githubusercontent.com/3886025/95125088-b9c0ce00-0754-11eb-8274-3bc01e4e878e.png)

**Comment by ZackMercury** [comment]
Ah, I'm pretty sure when I downloaded it last time there was only the "Source code", that's what I downloaded.
The build works fine.
